CREATE TABLE Users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(40) NOT NULL UNIQUE,
password VARCHAR(164) NOT NULL,
karma INT DEFAULT 10,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
lastlogin TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Comments (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
uuid INT UNSIGNED,
title VARCHAR(300) NOT NULL,
dentry VARCHAR(700) NOT NULL,
prev INT UNSIGNED DEFAULT 0,
parent INT UNSIGNED DEFAULT 0,
votes INT DEFAULT 0,
tags VARCHAR(50),
snowflake CHAR(10),
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Tags (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
dentry VARCHAR(100)
);

CREATE TABLE Friends (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
a INT UNSIGNED,
b INT UNSIGNED,
pending BOOLEAN DEFAULT 1
);

CREATE TABLE Chats (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
dentry VARCHAR(250),
t INT UNSIGNED,
f INT UNSIGNED,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

