CREATE TABLE Users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(40) NOT NULL UNIQUE,
password VARCHAR(164) NOT NULL,
karma INT UNSIGNED,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
lastlogin TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE Comments (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
dentry VARCHAR(700) NOT NULL,
prev INT UNSIGNED,
votes INT,
tags VARCHAR(50),
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE Tags (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
dentry VARCHAR(100)
)
